server:
  port: 8889
  servlet:
    context-path: /rabbitmq/cons
spring:
  # 配置 RabbitMQ 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
    # 虚拟 host 一般都是一个项目创建一个对应的host，我这边就使用 默认 /
    virtual-host: /
    template:
      mandatory: true
      receive-timeout: 5000
      reply-timeout: 5000
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 1.0
        max-interval: 10000
    listener:
      simple:
        retry:
          enabled: true
## 日志
logging:
  config: classpath:logback-spring.xml
