server:
  port: 8889
  servlet:
    context-path: /rabbitmq/cons
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
## 日志
logging:
  config: classpath:logback-spring.xml
