server:
  port: 8888
  servlet:
    context-path: /rabbitmq/prod
spring:
  # 配置 RabbitMQ 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    stream:
      username: guest
      password: guest
    # 虚拟 host 一般都是一个项目创建一个对应的host，我这边就使用 默认 /
    virtual-host: /
    # 开启 确认消息已发送到队列中(queue),如果不需要 消息确认可以把下面两行注释掉
    publisher-returns: true
    # 确认类型
    publisher-confirm-type: correlated
## 日志
logging:
  config: classpath:logback-spring.xml
